backend:
  name: github
  repo: stripesfensky/hugotesting

media_folder: /static/photos
public_folder: /photos

site_url: https://hugotesting-k2g6v.ondigitalocean.app

show_preview_links: false

slug:
  encoding: ascii
  clean_accents: true

editor:
  preview: false

collections:
  - name: article
    label: Articles
    label_singular: Articles
    folder: content/wiki
    format: toml-frontmatter
    icon: docs
    summary: "{{category}} &nbsp; // &nbsp; {{title}} &nbsp; // &nbsp; Last updated on {{commit_date | date('MMMM D, YYYY')}} at {{commit_date | date('h:mm:ss A')}}"
    sortable_fields: [category]
    fields:
      - name: title
        label: Title
        widget: string
      - name: tags
        label: Tags
        widget: select
        min: 1
        multiple: true
        options:
          - Advanced Animations
          - AnimatedFX
          - AVG Technologies
          - Celebration Station
          - Chuck E. Cheese in the Galaxy 5000
          - Chuck E. Cheese's
          - Circus Pizza
          - Creative Engineering
          - Creative Presentations
          - Disney Experiences
          - Five Nights at Freddy's
          - Five Nights at Freddy's (Movie)
          - Five Nights at Freddy's 2 (Movie)
          - Golding Leisure
          - Heimotion
          - Hofmann Figuren
          - Jim Henson's Creature Shop
          - Jungle Jim's
          - Magic Robotics, Inc. # Magic Robotics Inc.
          - Pasqually's Pizza and Wings # Pasqually's Pizza & Wings
          - Peter Piper Pizza
          - Pizza Time Theatre
          - Sally Corporation
          - Setmakers
          - ShowBiz Pizza Place
          - Six Flags
          - The Rock-afire Explosion (Movie)
          - Villalobos Producciones
          - VP Animations
          - Walt Disney Imagineering
          - Other Companies and Brands # Other Manufacturers
          - Other FECs
          # - Site Content # Cheese-E-Pedia (META)
          # - User-Generated Content (USERS/TRANSCRIPTIONS)

      - name: category
        label: Category
        widget: select
        min: 1
        options:
          - Ad Vehicles
          - Animatronic Control Systems
          - Animatronic Parts
          - Animatronic Preservation
          - Animatronic Shows
          - Animatronics
          - Arcades and Attractions
          - Characters
          - Commercials
          - Companies and Brands # Companies/Brands
          - Company Media
          - Costume Preservation
          - Costumed Characters
          - Documents # Merge in Corporate Documents
          - Employee Wear
          - Events
          - Family Vision
          - History
          - In-Store Merchandise
          - Live Shows
          - Locations # Merge in Cancelled Locations
          - Menu Items
          - Movies
          - News Footage
          - Other Software and Systems # Other Systems
          - Products
          - Programming Systems
          - Promotional Material
          - Puppets
          - Remodels and Initiatives
          - Retrofits
          - ShowBiz Pizza Programs
          - Showtape Formats
          - Showtapes
          - Simulators
          - Social Media and Websites
          - Stage Variations
          - Store Fixtures
          - Tickets
          - Tokens
          - Video Games
          # - Site Content # Meta (META)
          # - Reviews (REVIEWS)
          # - Photos (PHOTOS)
          # - Transcriptions (TRANSCRIPTIONS)
          # - User (USER)
          # - Videos (VIDEOS)

      - name: thumbnail
        label: Page Thumbnail
        widget: image
        choose_url: false
        required: false
        hint: A photo page is required for the thumbnail image to display properly.

      - name: citations
        label: Citations
        label_singular: Citation
        widget: list
        field: { name: citation, label: Citation, widget: string }
        required: false
      
      - name: contributors
        label: Contributors
        label_singular: Contributor
        widget: list
        field: { name: contributor, label: Contributor, widget: string }
        required: false

      - name: start
        label: Start Date
        widget: string
        hint: Leave empty if not needed. Otherwise, enter the date in format YYYY-MM-DD. Replace with 0s for unknown year/month/day.
        pattern: ['^$|\d{4}-\d{2}-\d{2}$', Date must be in format YYYY-MM-DD]
        required: false

      - name: end
        label: End Date
        widget: string
        hint: Leave empty if not needed. Otherwise, enter the date in format YYYY-MM-DD. Replace with 0s for unknown year/month/day.
        pattern: ['^$|\d{4}-\d{2}-\d{2}$', Date must be in format YYYY-MM-DD]
        required: false
      
      - name: body
        label: Body
        widget: richtext
        buttons: [
          bold,
          italic,
          strikethrough,
          heading-one,
          heading-two,
          heading-three,
          heading-four,
          heading-five,
          heading-six,
          bulleted-list,
          numbered-list,
          quote
        ]
        editor_components: []
        required: false

      - name: addfields
        label: Additional Fields
        widget: list
        fields:
          - name: addfield
            label: Additional Field
            widget: object
            types:
              - name: akafield
                label: AKA Field
                widget: object
                fields:
                  - name: aka
                    label: AKA
                    widget: string
              - name: animatronicsfield
                label: Animatronics Field
                widget: object
                fields:
                  - name: animatronics
                    label: Animatronics
                    widget: list
                    fields:
                    - name: animatronic
                      label: Animatronic
                      widget: object
                      fields:
                        - name: animatronic_title
                          label: Title
                          widget: string
                        - name: animatronic_debut
                          label: Debut
                          widget: string
                          hint: Leave empty if not needed. Otherwise, enter the date in format YYYY-MM-DD. Replace with 0s for unknown year/month/day.
                          pattern: ['^$|\d{4}-\d{2}-\d{2}$', Date must be in format YYYY-MM-DD]
                          required: false
                        - name: animatronic_removal
                          label: Removal
                          widget: string
                          hint: Leave empty if not needed. Otherwise, enter the date in format YYYY-MM-DD. Replace with 0s for unknown year/month/day.
                          pattern: ['^$|\d{4}-\d{2}-\d{2}$', Date must be in format YYYY-MM-DD]
                          required: false
                        - name: animatronic_serial
                          label: Serial
                          widget: string
                          required: false
                        - name: animatronic_status
                          label: Status
                          widget: string
                          required: false
