# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: stripesfensky/hugotesting

media_folder: /static/photos
public_folder: /photos

site_url: https://hugotesting-k2g6v.ondigitalocean.app

show_preview_links: false

slug:
  encoding: ascii
  clean_accents: true

editor:
  preview: false

collections:
  - name: article
    label: Articles
    label_singular: Articles
    folder: content/wiki
    format: toml-frontmatter
    icon: desktop_landscape
    summary: '{{title}} ({{date}})'
    fields:
      - name: title
        label: Title
        widget: string

      - name: thumbnail
        label: Page Thumbnail
        widget: image
        choose_url: false
        required: false

      - name: citations
        label: Citations
        label_singular: Citation
        widget: list
        field:
          - name: citation
            label: Citation (text or URL)
            widget: string
        required: false
      
      - name: contributors
        label: Contributors
        label_singular: Contributor
        widget: list
        field:
          - name: contributor
            label: Username
            widget: string
        required: false

      - name: daterange
        label: Date or Date Range
        widget: object
        fields:
          - name: enabled
            label: Enabled
            widget: boolean
