# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: stripesfensky/hugotesting
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "static/photos"
public_folder: "/photos"

site_url: https://hugotesting-k2g6v.ondigitalocean.app

show_preview_links: false

slug:
  encoding: "ascii"
  clean_accents: true

editor:
  preview: false

collections:
  - name: "locations"
    label: "Locations"
    label_singular: "Location"
    icon: "pin_drop"
    folder: "content/wiki"
    # filter: { field: "tags", value: "Locations" }
    create: true
    extension: md
    format: toml-frontmatter
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Page Thumbnail"
        name: "pageThumbnailFile"
        widget: "image"
        choose_url: false
        required: false

      - label: "Citations"
        name: "citations"
        widget: "list"
        field: { label: "Citation", name: "citation" }
        required: false

      - label: "Contributors"
        name: "contributors"
        widget: "list"
        field: { label: "Username", name: "contributor" }
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
        buttons: [
          bold,
          italic,
          strikethrough,
          heading-one,
          heading-two,
          heading-three,
          heading-four,
          heading-five,
          heading-six,
          bulleted-list,
          numbered-list,
          quote
        ]
        required: false
    
      - label: "Start Date"
        name: "startDate"
        widget: "string"
        hint: "Enter the date in format YYYY-MM-DD. Replace with 0s for unknown year/month/day."
        pattern: ['\d{4}-\d{2}-\d{2}$', "Date must be in format YYYY-MM-DD"]
        required: false

      - label: "End Date"
        name: "endDate"
        widget: "string"
        hint: "Enter the date in format YYYY-MM-DD. Leave empty if unknown or not applicable. Replace with 0s for unknown year/month/day."
        pattern: ['\d{4}-\d{2}-\d{2}$', "Date must be in format YYYY-MM-DD"]
        required: false

      - label: "Concept Unification Date"
        name: "cuDate"
        widget: "string"
        hint: "Enter the date in format YYYY-MM-DD. Leave empty if unknown or not applicable. Replace with 0s for unknown year/month/day."
        pattern: ['\d{4}-\d{2}-\d{2}$', "Date must be in format YYYY-MM-DD"]
        required: false

      - label: "Map Coordinates"
        name: "latitudeLongitude"
        widget: "object"
        fields: 
          - { label: "Latitude", name: "latitude", widget: "number", value_type: "float" }
          - { label: "Longitude", name: "longitude", widget: "number", value_type: "float" }
        required: false

      - label: "Store Number"
        name: "storeNumber"
        widget: "number"
        required: false

      - label: "Square Footage"
        name: "sqft"
        widget: "number"
        value_type: "float"
        required: false

      - label: "Animatronic Shows"
        name: "animatronic_shows"
        widget: "list"
        fields:
          - label: "Animatronic Show"
            name: "animatronic_show"
            widget: "object"
            fields:
              - label: "Page Title"
                name: "show_title"
                widget: "string"
              - label: "Debut Date"
                name: "show_debutdate"
                widget: "string"
                hint: "Enter the date in format YYYY-MM-DD. Leave empty if unknown or not applicable. Replace with 0s for unknown year/month/day."
                pattern: ['\d{4}-\d{2}-\d{2}$', "Date must be in format YYYY-MM-DD"]
              - label: "Removal Date"
                name: "show_removaldate"
                widget: "string"
                hint: "Enter the date in format YYYY-MM-DD. Leave empty if unknown or not applicable. Replace with 0s for unknown year/month/day."
                pattern: ['\d{4}-\d{2}-\d{2}$', "Date must be in format YYYY-MM-DD"]
        required: false
#
#     - label: "Attractions"
#
#     - label: "Animatronics"
#
#     - label: "Franchisees"
#
#     - label: "Remodels"
#
      - label: "Page Tags"
        name: "tags"
        widget: "hidden"
        default: ["Locations"]

#     - label: "Page Categories"

  - name: "animatronic_shows"
    label: "Animatronic Shows"
    label_singular: "Animatronic Show"
    icon: "curtains"
    folder: "content/wiki"
    # filter: { field: "tags", value: "Animatronic Shows" }
    create: true
    extension: md
    format: toml-frontmatter
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Page Thumbnail"
        name: "pageThumbnailFile"
        widget: "image"
        choose_url: false
        required: false

      - label: "Citations"
        name: "citations"
        widget: "list"
        field: { label: "Citation", name: "citation" }
        required: false

      - label: "Contributors"
        name: "contributors"
        widget: "list"
        field: { label: "Username", name: "contributor" }
        required: false

      - label: "Body"
        name: "body"
        widget: "markdown"
        buttons: [
          bold,
          italic,
          strikethrough,
          heading-one,
          heading-two,
          heading-three,
          heading-four,
          heading-five,
          heading-six,
          bulleted-list,
          numbered-list,
          quote
        ]
        required: false

      - label: "Page Tags"
        name: "tags"
        widget: "hidden"
        default: ["Animatronic Shows"]